### ISSUE TITLE
Slack talk exception

### ISSUE THREAD

**Issue by keith** [rawdigits/wee-slack#126]
Occasionally when I run `/slack talk someone` it fails with this exception

```
python: error in function "slack_command_cb"
python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/Users/ksmiley/dev/dotfiles/weechat/python/autoload/wee_slack.py", line 871, in slack_command_cb
python: stdout/stderr:     command = cmds[function_name](current_buffer, args)
python: stdout/stderr:   File "/Users/ksmiley/dev/dotfiles/weechat/python/autoload/wee_slack.py", line 919, in wrapper
python: stdout/stderr:     return f(current_buffer, *args, **kwargs)
python: stdout/stderr:   File "/Users/ksmiley/dev/dotfiles/weechat/python/autoload/wee_slack.py", line 949, in command_talk
python: stdout/stderr:     servers.find(current_domain_name()).users.find(args).open()
python: stdout/stderr: AttributeError: 'NoneType' object has no attribute 'open'
```

This isn't 100% but I thought I should put it on the radar. Let me know if I can provide anything else useful.

**Comment by keith** [comment]
Ah this might be happening when attempting to talk to an invalid user name.

**Comment by rawdigits** [comment]
This code has been changed to fail more gracefully and not drop a stack trace. Going to close for now. LMK if you see further issues.

**Comment by keith** [comment]
Thanks!
