### ISSUE TITLE
`afk` referenced before assignment

### ISSUE THREAD

**Issue by keith** [rawdigits/wee-slack#150]
I started noticing this new exception in the weechat buffer:

```
python: wrong arguments for function "nicklist_search_nick" (script: slack_extension)
python: wrong arguments for function "nicklist_remove_nick" (script: slack_extension)
python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/Users/ksmiley/dev/dotfiles/weechat/python/autoload/wee_slack.py", line 1274, in slack_websocket_cb
python: stdout/stderr:     proc[function_name](message_json)
python: stdout/stderr:   File "/Users/ksmiley/dev/dotfiles/weechat/python/autoload/wee_slack.py", line 1332, in process_presence_change
python: stdout/stderr:     server.users.find(identifier).set_inactive()
python: stdout/stderr:   File "/Users/ksmiley/dev/dotfiles/weechat/python/autoload/wee_slack.py", line 803, in set_inactive
python: stdout/stderr:     channel.update_nicklist(self.identifier)
python: stdout/stderr:   File "/Users/ksmiley/dev/dotfiles/weechat/python/autoload/wee_slack.py", line 441, in update_nicklist
python: stdout/stderr:     w.nicklist_add_nick(self.channel_buffer, afk, user.name, user.color_name, "", "", 1)
python: stdout/stderr: UnboundLocalError: local variable 'afk' referenced before assignment
python: error in function "slack_websocket_cb"
```

Looks like that's getting hit here:

https://github.com/rawdigits/wee-slack/blob/master/wee_slack.py#L441

Which must mean that the first condition [here](https://github.com/rawdigits/wee-slack/blob/master/wee_slack.py#L422-L432) evaluates to false and `afk` never gets set.

**Comment by alexbarton** [comment]
I'm seeing this as well.

**Comment by fuzzy76** [comment]
:+1:
