### ISSUE TITLE
users.find(self.name) returns None on channel join

### ISSUE THREAD

**Issue by scotte** [rawdigits/wee-slack#190]
users.find(self.name) appears to return None when joining channels.

Updated: Originally I incorrectly thought this was preventing me from joining channels. My channels get joined, they just show up as inactive in weechat, for some reason. This is noticeable if buffers.log.mark_inactive is set, which puts parenthesis around inactive channels (such as those that have been /part'ed), making all slack channels appear to be parted.

Version info:

```
WeeChat 1.4 [compiled on Jan 29 2016 10:02:56]
slack_extension.py 0.99.9 (Extends weechat for typing notification/search/etc on slack.com)
```

Errors at script load:

```
python: wrong arguments for function "buffer_set" (script: slack_extension)
python: stdout/stderr: TypeError: must be string, not None
python: error in function "slack_websocket_cb"
```

Errors at channel join: 

```
python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/path/to/.weechat/python/autoload/wee_slack.py", line 961, in slack_command_cb
python: stdout/stderr:     command = cmds[function_name](current_buffer, args)
python: stdout/stderr:   File "/path/to/.weechat/python/autoload/wee_slack.py", line 1081, in command_join
python: stdout/stderr:     servers.find(domain).channels.find(args).open()
python: stdout/stderr:   File "/path/to/.weechat/python/autoload/wee_slack.py", line 554, in open
python: stdout/stderr:     async_slack_api_request(self.server.domain, self.server.token, SLACK_API_TRANSLATOR[self.type]["join"], {"user": users.find(self.name).identifier})
python: stdout/stderr: AttributeError: 'NoneType' object has no attribute 'identifier'
python: error in function "slack_command_cb"
```

**Comment by terminalmage** [comment]
This should be resolved with https://github.com/rawdigits/wee-slack/pull/215

**Comment by scotte** [comment]
Thanks, I'll test when #215 is merged and close/update this one as appropriate.
