### ISSUE TITLE
wee-slack can no longer connect

### ISSUE THREAD

**Issue by sappel34** [rawdigits/wee-slack#207]
The script stopped working today without any change from my side. Probably a  Slack API change? :

           │13:46:05     | python: registriertes Skript "slack_extension", Version 0.99.9 (Extends weechat for typing notification/search/etc on slack.com)
           │13:46:05     | DEBUG: Loading messages from cache.
           │13:46:05     | python: stdout/stderr: Traceback (most recent call last):
           │13:46:05     | python: stdout/stderr:   File "/home/sappel/.weechat/python/autoload/wee_slack.py", line 2225, in <module>
           │13:46:05     | python: stdout/stderr:     cache_load()
           │13:46:05     | python: stdout/stderr:   File "/home/sappel/.weechat/python/autoload/wee_slack.py", line 2053, in cache_load
           │13:46:05     | python: stdout/stderr:     j = json.loads(line)
           │13:46:05     | python: stdout/stderr:   File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
           │13:46:05     | python: stdout/stderr:     return _default_decoder.decode(s)
           │13:46:05     | python: stdout/stderr:   File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
           │13:46:05     | python: stdout/stderr:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
           │13:46:05     | python: stdout/stderr:   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
           │13:46:05     | python: stdout/stderr:     obj, end = self.scan_once(s, idx)
           │13:46:05     | python: stdout/stderr:   File "/usr/lib/python2.7/json/decoder.py", line 38, in errmsg
           │13:46:05     | python: stdout/stderr:     lineno, colno = linecol(doc, pos)
           │13:46:05     | python: stdout/stderr: TypeError: 'NoneType' object is not callable
           │13:46:05 =!= | python: Datei "/home/sappel/.weechat/python/autoload/wee_slack.py" Analyse nicht möglich

**Comment by sappel34** [comment]
problem solved by deleting slack.cache file
