### ISSUE TITLE
Unable to load cache

### ISSUE THREAD

**Issue by Succo** [rawdigits/wee-slack#248]
I get this error when starting weechat on debian testing;

```
python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/home/fabrice/.weechat/python/autoload/wee_slack.py", line 2301, in <module>
python: stdout/stderr:     cache_load()
python: stdout/stderr:   File "/home/fabrice/.weechat/python/autoload/wee_slack.py", line 2122, in cache_load
python: stdout/stderr:     j = json.loads(line)
python: stdout/stderr:   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
python: stdout/stderr:     return _default_decoder.decode(s)
python: stdout/stderr:   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
python: stdout/stderr:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
python: stdout/stderr:   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
python: stdout/stderr:     raise ValueError("No JSON object could be decoded")
python: stdout/stderr: ValueError: No JSON object could be decoded
```

This prevent the plugin from loading.

**Comment by Succo** [comment]
It does work after deleting the cache though so maybe just adding a try/cache would do it.

I wonder why the json was broken though. Could it be because I turned off my computer without exiting properly?

**Comment by Succo** [comment]
Great thanks, I suggest, you add better file handling to limit the file getting corrupted. I've left an example of that in a PR https://github.com/rawdigits/wee-slack/pull/249
