### ISSUE TITLE
Favouriting a channel leads to traceback

### ISSUE THREAD

**Issue by tfheen** [rawdigits/wee-slack#85]
Clicked the star in the web ui, got traceback:

```
21:35:34   weechat     | python: stdout/stderr: Traceback (most recent call last):                                                           
21:35:34   weechat     | python: stdout/stderr:   File "/home/tfheen/.weechat/python/autoload/wee_slack.py", line 1001, in slack_websocket_cb
21:35:34   weechat     | python: stdout/stderr:     proc[function_name](message_json)                                                            
21:35:34   weechat     | python: stdout/stderr:   File "/home/tfheen/.weechat/python/autoload/wee_slack.py", line 1043, in process_channel_marked
21:35:34   weechat     | python: stdout/stderr:     channel.mark_read(False)                                  
21:35:34   weechat     | python: stdout/stderr: AttributeError: 'NoneType' object has no attribute 'mark_read'
21:35:34   weechat =!= | python: error in function "slack_websocket_cb"
```

**Comment by tfheen** [comment]
Can't reproduce this any longer, so closing.
